// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoBYCk4Kt9oE3vMIJ4lMM_3ZtSMe7fQnw',
    appId: '1:927784046589:android:27fadb3e95953bbe6e1394',
    messagingSenderId: '927784046589',
    projectId: 'east-d0939',
    storageBucket: 'east-d0939.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdjeO43g0JcksWsa3iJyW9eraETe9F2sM',
    appId: '1:927784046589:ios:21a20bc0116cf2916e1394',
    messagingSenderId: '927784046589',
    projectId: 'east-d0939',
    storageBucket: 'east-d0939.appspot.com',
    iosBundleId: 'com.example.east',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZGRmLQNXyEYaEmHhnxsNHyAOIlVTXm8A',
    appId: '1:927784046589:web:4dc57a569224df7f6e1394',
    messagingSenderId: '927784046589',
    projectId: 'east-d0939',
    authDomain: 'east-d0939.firebaseapp.com',
    storageBucket: 'east-d0939.appspot.com',
    measurementId: 'G-RMHT90DGQC',
  );
}
